config/routes.rb
PopulationApi::Application.routes.draw do

    root to: 'population#get_csv'

    get 'population/index'
    get 'population/get_csv'
    get 'population/get_pop'

    get 'zips/index'
    get 'zips/import' => 'zips#my_import'

    get 'cbsas/index'
    get 'cbsas/import' => 'cbsas#my_import'

    resources :zips do
        collection {post :import}
    end

    resources :cbsas do
        collection {post :import}
    end

    # Api definition
    # namespace :api, defaults: { format: :json },
    #                 path: '/api/'  do
    #     resources :zip
    # end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cbsa.rb
class Cbsa < ApplicationRecord

    require 'csv'
    require 'activerecord-import/base'
    require 'activerecord-import/active_record/adapters/sqlite3_adapter'

    def self.my_import(file)

        cbsas = []
        CSV.foreach(file.path, headers: true, header_converters: [:downcase, :symbol], encoding: 'ISO-8859-1') do |row|
            cbsa_hash = row.to_hash
            # if cbsa_hash[:cbsa] != ''
                cbsas << Cbsa.new({
                    cbsa: cbsa_hash[:cbsa],
                    mdiv: cbsa_hash[:mdiv],
                    name: cbsa_hash[:name],
                    lsad: cbsa_hash[:lsad],
                    popestimate2014: cbsa_hash[:popestimate2014],
                    popestimate2015: cbsa_hash[:popestimate2015]
                })
            # end
        end
        Cbsa.import cbsas
        
    end

end

app/models/zip.rb
class Zip < ApplicationRecord

    require 'csv'
    require 'activerecord-import/base'
    require 'activerecord-import/active_record/adapters/sqlite3_adapter'

    def self.my_import(file)

        zips = []
        CSV.foreach(file.path, headers: true, header_converters: [:downcase, :symbol], encoding: 'ISO-8859-1') do |row|
            zip_hash = row.to_hash
            zips << Zip.new({
                zip: zip_hash[:zip],
                cbsa: zip_hash[:cbsa]
            })
        end
        Zip.import zips
        
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cbsas_controller.rb
class CbsasController < ApplicationController
    def index
        @cbsas = Cbsa.all
    end

    def import
        Cbsa.my_import(params[:file])
        redirect_to root_url, notice: 'Successfully imported data'
    end
end

app/controllers/population_controller.rb
class PopulationController < ApplicationController

    def index
        @zips = Zip.all
        @cbsas = Cbsa.all
    end

    def get_csv
        zip_file = File.new('vendor/zip_to_cbsa.csv')
        cbsa_file = File.new('vendor/cbsa_to_msa.csv')

        Zip.my_import(zip_file)
        Cbsa.my_import(cbsa_file)
        redirect_to action: 'index'
    end

    def get_pop
        zips = Zip.all
        cbsas = Cbsa.all

        redirect_to action: 'index', @data => zips
    end

end

app/controllers/zips_controller.rb
class ZipsController < ApplicationController
    def index
        @zips = Zip.all
    end

    def import
        Zip.my_import(params[:file])
        redirect_to root_url, notice: 'Successfully imported data'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cbsas_helper.rb
module CbsasHelper
end

app/helpers/population_helper.rb
module PopulationHelper
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/cbsas/import.html.erb
<h1>Cbsas#import</h1>
<p>Find me in app/views/cbsas/import.html.erb</p>

app/views/cbsas/index.html.erb
<%= flash[:notice] %>
<div>
    <h4>Import data</h4>
    <%= form_tag import_cbsas_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import from file" %>
    <% end %>
</div>
<table>
    <thead>
        <tr>
            <th>CBSA</th>
            <th>NAME</th>
        </tr>
    </thead>
    <tbody>
        <% @cbsas.each do |cbsa| %>
        <tr>
            <td><%= cbsa.cbsa %></td>
            <td><%= cbsa.name %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PopulationApi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/population/get_csv.html.erb
<h1>Population#get_csv</h1>
<p>Find me in app/views/population/get_csv.html.erb</p>

app/views/population/index.html.erb
<h1>Population API</h1>

<h2>Enter Zip Code</h2>
<%= form_tag ({action: :get_pop}) do %>
    <%= file_field_tag :number %>
    <%= submit_tag "Submit" %>
<% end %>

<table>
    <thead>
        <tr>
            <th>ZIP</th>
            <th>CBSA</th>
        </tr>
    </thead>
    <tbody>
        <% @data.each do |zip| %>
        <tr>
            <td><%= zip.zip %></td>
            <td><%= zip.cbsa %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/zips/import.html.erb
<h1>Zips#import</h1>
<p>Find me in app/views/zips/import.html.erb</p>

app/views/zips/index.html.erb
<%= flash[:notice] %>
<div>
    <h4>Import data</h4>
    <%= form_tag import_zips_path, multipart: true do %>
        <%= file_field_tag :file %>
        <%= submit_tag "Import from file" %>
    <% end %>
</div>
<table>
    <thead>
        <tr>
            <th>ZIP</th>
            <th>CBSA</th>
        </tr>
    </thead>
    <tbody>
        <% @zips.each do |zip| %>
        <tr>
            <td><%= zip.zip %></td>
            <td><%= zip.cbsa %></td>
        </tr>
        <% end %>
    </tbody>
</table>